In [1]:
import numpy as np

In [2]:
np.__version__

'1.20.3'

help(np.array)

In [3]:
vetor1 = np.array([0,1,2,3,4,5,6,7,8])

In [4]:
type(vetor1)

numpy.ndarray

In [5]:
vetor1.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36])

In [6]:
lst = [0,1,2,3,4,5,6,7,8]

In [7]:
lst.sort()

In [8]:
vetor1[1]

1

In [9]:
vetor1[0] = 100

In [10]:
vetor1

array([100,   1,   2,   3,   4,   5,   6,   7,   8])

In [11]:
print(vetor1.shape)

(9,)


In [12]:
vetor2 = np.arange(0.,4.5,.5)

In [13]:
type(vetor2)

numpy.ndarray

In [14]:
np.shape(vetor2)

(9,)

In [15]:
print(vetor2.dtype)

float64


In [16]:
print(vetor2)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4. ]


In [17]:
x = np.arange(1, 10, 0.25)

In [18]:
print(x)

[1.   1.25 1.5  1.75 2.   2.25 2.5  2.75 3.   3.25 3.5  3.75 4.   4.25
 4.5  4.75 5.   5.25 5.5  5.75 6.   6.25 6.5  6.75 7.   7.25 7.5  7.75
 8.   8.25 8.5  8.75 9.   9.25 9.5  9.75]


In [19]:
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [20]:
z = np.eye(3)

In [21]:
z

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
d = np.diag(np.array([1,2,3,4]))

In [23]:
d

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [24]:
c = np.array([1+2j, 3+4j, 5+6*1j])

In [25]:
c

array([1.+2.j, 3.+4.j, 5.+6.j])

In [26]:
b = np.array([True, False])

In [27]:
b

array([ True, False])

In [28]:
s = np.array(['Python', 'R', 'Julia'])

In [29]:
s

array(['Python', 'R', 'Julia'], dtype='<U6')

In [30]:
np.linspace(0,10)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [31]:
print(np.linspace(0,10,15))

[ 0.          0.71428571  1.42857143  2.14285714  2.85714286  3.57142857
  4.28571429  5.          5.71428571  6.42857143  7.14285714  7.85714286
  8.57142857  9.28571429 10.        ]


In [32]:
print(np.linspace(0,5,10))

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]
